version: "3.7"

services:
    backend:
        build: backend
        hostname: backend
        restart: always
        ports:
            - ${DJANGO_PORT}:${DJANGO_PORT}
        env_file:
            - .env
        environment:
            DJANGO_SECRET: ${DJANGO_SECRET}
            DJANGO_PORT: ${DJANGO_PORT}
            DEBUG: ${DEBUG}
        networks:
            - backend-frontend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${DJANGO_PORT}/"]
            interval: 30s
            timeout: 10s
            retries: 5

    website:
        build: frontend
        env_file:
            - .env
        environment:
            API_URL: ${EXTERNAL_API_URL}
            NEXT_PORT: ${NEXT_PORT}
        ports:
            - ${NEXT_PORT}:${NEXT_PORT}
        volumes:
            - ./frontend/src:/code/src
            - ./frontend/node_modules:/code/node_modules
        networks:
            - backend-frontend
        depends_on:
            - backend
        restart: always

    tunnel:
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: tunnel run
        environment:
            TUNNEL_TOKEN: ${TUNNEL_TOKEN}
        networks:
            - backend-frontend

networks:
    backend-frontend:
