# Generated by Django 5.1.4 on 2025-01-14 05:42

import data.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30, unique=True, validators=[data.models.validate_username])),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('residentialStatus', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commuter')], default='Residental', max_length=255)),
                ('standing', models.CharField(choices=[('FRE', 'Freshman'), ('SOP', 'Sophomore'), ('JUN', 'Junior'), ('SEN', 'Senior')], default='Freshman', max_length=255)),
                ('club', models.ManyToManyField(blank=True, to='data.club')),
                ('major', models.ManyToManyField(blank=True, to='data.major')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=999, null=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('UTC_of_event', models.DateTimeField()),
                ('open_to_the_public', models.BooleanField()),
                ('eventTags', models.CharField(choices=[('SOCIAL', 'Social'), ('SPORT', 'Sport'), ('HOBBY', 'Hobby'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.location')),
                ('hosts', models.ManyToManyField(related_name='hosts_of', to='data.user')),
                ('participants', models.ManyToManyField(related_name='event_participants', to='data.user')),
            ],
        ),
    ]
