# Generated by Django 5.1.4 on 2025-02-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hosts',
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to='data.user'),
        ),
    ]
