# Generated by Django 5.1.4 on 2025-02-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_event_hosts_event_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to='data.user'),
        ),
    ]
