# Generated by Django 5.1.4 on 2025-02-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_event_hosts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hosts',
            new_name='host',
        ),
    ]
