# Generated by Django 5.1.2 on 2024-10-30 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[], default=('N', 'None'), max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('S', 'Social'), ('B', 'Bike'), ('W', 'Walk')], default=('S', 'Social'), max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[], default=('SAC', 'Student Activity Center'), max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='maxCapacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='publicStatus',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default=('PUB', 'Public'), max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='interestTag',
            field=models.ManyToManyField(default=('N', 'None'), to='friends_app_api.interestmodel'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('major', models.CharField(choices=[('AFS', 'Africana Studies'), ('ANT', 'Anthropology'), ('AMS', 'Applied Mathematics and Statistics')], default=('AFS', 'Africana Studies'), max_length=255)),
                ('clubs', models.CharField(choices=[], default=('N', 'None'), max_length=255)),
                ('points', models.PositiveIntegerField()),
                ('residentialStatus', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commuter')], default=('RES', 'Residential'), max_length=255)),
                ('standing', models.CharField(choices=[('FRE', 'Freshman'), ('SOP', 'Sophomore'), ('JUN', 'Junior'), ('SEN', 'Senior')], default=('FRE', 'Freshman'), max_length=255)),
                ('userinterest', models.ManyToManyField(to='friends_app_api.interestmodel')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=('N', 'None'), on_delete=django.db.models.deletion.CASCADE, to='friends_app_api.user'),
        ),
    ]
