# Generated by Django 5.1.2 on 2025-01-13 20:21

import django.core.validators
import django.db.models.deletion
import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[test_app.models.validate_username])),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('residentialStatus', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commuter')], default='Residental', max_length=255)),
                ('standing', models.CharField(choices=[('FRE', 'Freshman'), ('SOP', 'Sophomore'), ('JUN', 'Junior'), ('SEN', 'Senior')], default='Freshman', max_length=255)),
                ('club', models.ManyToManyField(blank=True, to='test_app.club')),
                ('major', models.ManyToManyField(blank=True, to='test_app.major')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=999, null=True)),
                ('maxCapacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('eventDate', models.DateTimeField()),
                ('publicStatus', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=30)),
                ('eventTags', models.CharField(choices=[('SOCIAL', 'Social'), ('SPORT', 'Sport'), ('HOBBY', 'Hobby'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.location')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
    ]
