# Generated by Django 5.1.2 on 2025-01-10 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=999, null=True)),
                ('maxCapacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('eventDate', models.DateTimeField()),
                ('publicStatus', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=30)),
                ('eventTags', models.CharField(choices=[('SOCIAL', 'Social'), ('SPORT', 'Sport'), ('HOBBY', 'Hobby'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
    ]
