# Generated by Django 5.1.4 on 2024-12-24 19:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(default=datetime.date(1997, 10, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventTags',
            field=models.CharField(choices=[('SOCIAL', 'SOCIAL'), ('SPORT', 'SPORT'), ('HOBBY', 'HOBBY'), ('OTHER', 'OTHER')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='maxCapacity',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(250)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='publicStatus',
            field=models.CharField(choices=[('👋', 'Open 👋'), ('🚪', 'Closed 🚪')], default='Open', max_length=30),
            preserve_default=False,
        ),
    ]
