# Generated by Django 5.1.4 on 2024-12-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_event_eventtags_alter_event_publicstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='eventName',
        ),
    ]
