# Generated by Django 5.1.2 on 2025-01-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_rename_name_event_eventname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.event')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='test_app.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='test_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='invites',
            field=models.ManyToManyField(related_name='events_invited_to', through='test_app.Invite', to='test_app.user'),
        ),
    ]
