# Generated by Django 5.1.2 on 2025-01-08 20:25

import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_user_bio_alter_user_club_alter_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[test_app.models.validate_username]),
        ),
    ]
