# Generated by Django 5.1.2 on 2025-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ManyToManyField(blank=True, null=True, to='test_app.club'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ManyToManyField(blank=True, null=True, to='test_app.major'),
        ),
    ]
